config/routes.rb
Rails.application.routes.draw do
  get 'pets_toggle/index'
  devise_for :users, controllers: {registrations: "registrations"}
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :pets do
    delete 'pets/:id/image_remove', to: 'pets#remove_image', as: 'pet_image_remove'
    get '/pets/:id/image_remove' => 'pets#remove_image'
  end
  delete 'pets/:id/delete' => 'pets#destroy', as: 'pets_delete'
  get '/pets/:id/delete' => 'pets#destroy'

  resources :found_pets do
    delete 'found_pets/:id/image_remove', to: 'found_pets#remove_image', as: 'pet_image_remove'
    get '/found_pets/:id/image_remove' => 'found_pets#remove_image'
  end
  delete 'found_pets/:id/delete' => 'found_pets#destroy', as: 'found_pets_delete'
  get '/found_pets/:id/delete' => 'found_pets#destroy'

  root "home#index"
  get  'about/index', to:'about#index'
  get  'contact/index', to:'contact#index'

end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :image
  has_many :comments, as: :commentable
  has_many :record_details, as: :record_detailable, dependent: :destroy

  validates :image, blob: { content_type: :image, size_range: 1..5.megabyte }

  validates_presence_of :name, :description, :species, :breed, :lost_on, :latitude, :longitude, on: :create
  has_many :pets

  def lost_on_format
    lost_on.strftime('%a, %d %b %Y') if lost_on.present?
  end

  # callbacks
  before_save :handel_decimal_values
  after_create :no_image_handle

  def handel_decimal_values
    self.latitude = latitude.to_f if latitude.present?
    self.longitude = longitude.to_f if longitude.present?
  end

  def no_image_handle
    if species == 'Cat' && !image.attached?
      image.attach(
        io: File.open(Rails.root.join('app', 'assets', 'images',
                                      'cat.jpg')), filename: 'cat.jpg'
      )
    end

    if species == 'Dog' && !image.attached?
      image.attach(
        io: File.open(Rails.root.join('app', 'assets', 'images',
                                      'dog.jpg')), filename: 'dog.jpg'
      )
    end

    if species == 'Bird' && !image.attached?
      image.attach(
        io: File.open(Rails.root.join('app', 'assets', 'images',
                                      'bird.jpg')), filename: 'bird.jpg'
      )
    end

    unless image.attached?
      image.attach(
        io: File.open(Rails.root.join('app', 'assets', 'images',
                                      'no_image.jpg')), filename: 'no_image.jpg'
      )
    end
  end

  def find_record_details
    record_details[0]
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # check input date
  include DateHelper

  # users can not craete, update, delet if they are not logged in!
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_pet, only: %i[edit update]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all.order('created_at DESC')
  end

  # GET /pets/1 or /pets/1.json
  def show
    @pet = Pet.find(params[:id])
    @pet.as_json.merge(image: url_for(@pet.image)) unless @pet.image.blank?
    @pet
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])
  end

  # POST /pets or /pets.json
  def create
    if params[:form_on_submit]
      if check_date_helper(pet_params[:lost_on])
        respond_to do |format|
          format.html { redirect_to new_pet_path, alert: "Date #{pet_params[:lost_on].to_date} is not valid!" }
        end
      else
        @pet = Pets::PetCreateService.call(current_user, data)
        respond_to do |format|
          if @pet.save!
            RecordDetails::RecordDetailService.call(@pet, record_detail_data)

            format.html { redirect_to pets_toggle_index_path, notice: 'Pet was successfully created' }
            format.json { render :show, status: :created, location: pet }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: pet.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    if params[:form_on_update]
      if pet_params[:lost_on].present? && check_date_helper(pet_params[:lost_on])
        respond_to do |format|
          format.html { redirect_to edit_pet_path(@pet), alert: "Date #{pet_params[:lost_on].to_date} is not valid!" }
        end
      else
        respond_to do |format|
          if @pet.update(pet_params)
            @pet.record_details.update(record_detail_data) if record_detail_data.present?
            format.html { redirect_to @pet, notice: 'Pet was successfully updated' }
            format.json { render :show, status: :ok, location: pet }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: pet.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet = Pet.find(params[:id])
    if @pet.destroy
      respond_to do |format|
        format.html { redirect_to pets_toggle_index_path, notice: 'Pet was successfully destroyed' }
        format.json { head :no_content }
      end
    end
  end

  def remove_image
    @pet = Pet.find(params[:pet_id])
    if @pet.image.present?
      @pet.image.delete
      respond_to do |format|
        format.html { redirect_to @pet, notice: 'Image successfully removed' }
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_pet_path(@pet), alert: 'No image available!' }
      end
    end
  end

  private

  def data
    pet_params.to_h.compact
  end

  def record_detail_data
    location_params.to_h.compact
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_pet
    @pet = Pet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pet_params
    params.require(:pet).permit(:name, :description, :species, :breed, :lost_on, :latitude, :longitude, :image,
                                :other_info, :injured, :search)
  end

  def location_params
    params.require(:pet).permit(:route, :street_number, :neighborhood, :postal_code, :localicy, :country)
  end
end

app/views/pets/edit.html.erb
<h4 class="text-center">Edit <%= @pet.name.capitalize %></h4>
<hr />
<br />

<%= form_with model: @pet, local: true,
  data: {
    controller: "maps", action: "google-maps-callback@window->maps#initMap"
  } do |form| %>
    
  <% if @pet && @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pet.errors.count, "error" ) %> prohibited this pet from being saved:
      </h2>

      <ul>
        <% @pet.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>
      <div class="row">
        <div class="column column_1">
          <form>
            <div class="form-row">
              <div class="form-group col-md-4">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control" , placeholder:"Name" %>
              </div>
          
              <div class="form-group col-md-4">
                <%= form.label :species %>
                <%= form.select :species, ["Cat", "Dog" , "Bird" , "Hamster" , "Reptiles" , "Others" ], {},
                    class: "form-control" %>
              </div>
          
              <div class="form-group col-md-4">
                <%= form.label :breed %>
                <%= form.text_field :breed, class: "form-control" , placeholder:"Breed" %>
              </div>
            </div>
          
            <br />

            <div class="form-row">
              <div class="form-group col-md-4">
                <%= form.label :search %>
                <%= form.search_field :search, class: 'form-control' , placeholder: "Search City" , 'data-target'=> "maps.field" %>
              </div>
              
              <div class="form-group col-md-4">
                <%= form.label :latitude %>
                <%= form.text_field :latitude, class: "form-control" , 'data-target'=> "maps.latitude", :readonly => true%>
              </div>
              
              <div class="form-group col-md-4">
                <%= form.label :longitude %>
                <%= form.text_field :longitude, class: "form-control" , 'data-target'=> "maps.longitude", :readonly => true %>
              </div>
            </div>

            <br />

            <div class="form-row">
                <div class="form-group col-md-6">
                  <%= form.label :lost_on, "Lost On" %>
                    <span style="font-style:italic; font-size:12px">(date older then 3 years is not valid!)</span>
                    <%= form.text_field :lost_on, type: "date" , class:"form-control" %>
                </div>
            </div>

            <br />

            <div class="form-row">
              <div class="form-group col-md-6">
                <%= form.label :image %>
                  <br />
                <%= form.file_field :image %>
                  <br />
                <%= link_to 'Remove Image' , pet_pet_image_remove_path(@pet), method: :delete,
                    onclick: "return confirm('Are you sure?')" %>
              </div>

                <div class="form-group col-md-6">
                  <%= form.label :injured %> <br />
                  <%= form.check_box :injured %>
                </div>
            </div>

            <br />

            <button class="btn btn-dark hide">Location Details</button>
            <div class="location_details_hidden">
              <div class="form-row">
                <div class="form-group col-md-6">
                  <%= form.label :route %><br>
                    <%= form.text_field :route, class: 'form-control' , value:"not-available", 'data-target'=> "maps.route",
                      :readonly => true %>
                </div>
            
                <div class="form-group col-md-6">
                  <%= form.label :street_number %><br>
                    <%= form.text_field :street_number, class: 'form-control' , value:"not-available", 'data-target'=>
                      "maps.street_number", :readonly => true %>
                </div>
              </div>
            
              <div class="form-row">
                <div class="form-group col-md-6">
                  <%= form.label :neighborhood %><br>
                    <%= form.text_field :neighborhood, class: 'form-control' , value:"not-available", 'data-target'=>
                      "maps.neighborhood", :readonly => true %>
                </div>
            
                <div class="form-group col-md-6">
                  <%= form.label :postal_code %><br>
                    <%= form.text_field :postal_code, class: 'form-control' , value:"not-available", 'data-target'=>
                      "maps.postal_code", :readonly => true %>
                </div>
              </div>
            
              <div class="form-row">
                <div class="form-group col-md-6">
                  <%= form.label :locality %><br>
                    <%= form.text_field :locality, class: 'form-control' , value:"not-available", 'data-target'=> "maps.locality",
                      :readonly => true %>
                </div>
            
                <div class="form-group col-md-6">
                  <%= form.label :country %><br>
                    <%= form.text_field :country, class: 'form-control' , value:"not-available", 'data-target'=> "maps.country",
                      :readonly => true %>
                </div>
              </div>
            </div>

            <%= render "jquery_toggles/location_details_toggle" %>
            
            <br />
            <br />
            <div class="form-row">
              <div class="form-group col-md-6">
                <%= form.label :description, "Description" %>
                <%= form.text_area :description, placeholder: "max 100 character" , class:"form-control", maxlength: 100, rows: "3" %>
              </div>
              <div class="form-group col-md-6">
                <%= form.label :other_info, "Other Info" %>
                <%= form.text_area :other_info, placeholder: "max 30 character" , class:"form-control", maxlength: 30, rows: "3"%>
              </div>
            </div>
            
            <br />
            
            <div class="form-row text-center">
              <div class="form-group col-md-6">
                <%= form.submit "Save" , name: "form_on_update",class: "btn btn-default btn-success" , style: 'color:black; font-weight: bold; width: 15rem' %>
              </div>
            </div>
          </form>
        </div>

          <div class="column column_2">
            <form>
              <div class="form-group">
                <div data-maps-target="map" , class='map'></div>
              </div>
            </form>
          </div>
          
      </div>
    <hr />
  <% end %>

app/views/pets/index.html.erb
<% @pets = Pet %>

<div class="container-fluid content-row">
  <h5> <strong>Total Lost Pets - <%= @pets.count%> </strong></h5>
  <br />

  <div class="row" style="margin-bottom: 100px;">
    <% @pets.all.order("ID DESC").each do |pet| %>
      <div class="col-md-4 align-items-stretch" style="margin-bottom: 5%;">
        <div class="card h-100">

          <% if !pet.image.blank? %>
            <%=image_tag(pet.image, class: "card-img-top" ) %>
              <% else %>
                <img class="card-img-top" src="" alt="no image available!">
                <% end %>

                  <div class="card-body text-center d-flex flex-column">
                    <h5 class="card-title"> <strong>
                        <%= pet.name.upcase %>
                      </strong></h5>
                    <table class="table">
                      <tbody>
                        <tr>
                          <td>Species</td>
                          <td>
                            <%= pet.species.capitalize %>
                          </td>
                        </tr>
                        <tr>
                          <td>Breed</td>
                          <td>
                            <%= pet.breed.capitalize %>
                          </td>
                        </tr>
                        <tr>
                          <td>Lost on</td>
                          <td>
                            <%= pet.lost_on_format %>
                          </td>
                        </tr>
                      </tbody>
                    </table>

                    <%= link_to 'Read More' , pet, class: "mt-auto btn btn-primary" ,
                      style: "color: white; font-weight: bold" %>
                  </div>
                  <div class="card-footer text-muted text-center">
                    posted - <%= pet.created_at.strftime('%a, %d %b %Y') %>
                  </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<h3 class="text-center">Create New Record</h3>
<hr />
<br />


<%= form_with model: @pet, local: true, 
  data: { 
    controller: "maps", action: "google-maps-callback@window->maps#initMap"
  }  do |form| %>

  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(stop.errors.count, "error" ) %> prohibited this stop from being saved:
      </h2>

      <ul>
        <% stop.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="row">
  <div class="column column_1">
    <form>
      <div class="form-row">
        <div class="form-group col-md-4">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" , placeholder:"Name", :required => 'required' %>
        </div>
    
        <div class="form-group col-md-4">
          <%= form.label :species %>
          <%= form.select :species, ["Cat", "Dog" , "Bird" , "Hamster" , "Reptiles" , "Others" ], {},
              class: "form-control", :required => 'required' %>
        </div>
    
        <div class="form-group col-md-4">
          <%= form.label :breed %>
          <%= form.text_field :breed, class: "form-control" , placeholder:"Breed", :required => 'required' %>
        </div>
      </div>

      <br />

      <div class="form-row">
        <div class="form-group col-md-4">
          <%= form.label :search %>
          <%= form.search_field :search, class: 'form-control' , placeholder: "Search City" , 'data-target'=> "maps.field", :required => 'required' %>
        </div>
      
        <div class="form-group col-md-4">
          <%= form.label :latitude %>
          <%= form.text_field :latitude, class: 'form-control' , 'data-target'=> "maps.latitude", :readonly => true %>
        </div>
      
        <div class="form-group col-md-4">
          <%= form.label :longitude %>
          <%= form.text_field :longitude, class: 'form-control' , 'data-target'=> "maps.longitude", :readonly => true %>
        </div>
      </div>

      <br />

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.label :lost_on, "Lost On" %>
          <span style="font-style:italic; font-size:12px">(date older then 3 years is not valid!)</span>
          <%= form.text_field :lost_on, type: "date" , class:"form-control", :required => 'required' %>
        </div>
      </div>

      <br />

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.label :image %>
          <%= form.file_field :image, class: "form-control-file" %>
        </div>

        <div class="form-group col-md-6">
          <%= form.label :injured %> <br />
          <%= form.check_box :injured %>
        </div>
      </div>

      <br />

      <!-- Dundee Road, Queens Peak, Singapore -->
      <button class="btn btn-dark hide">Location Details</button>
      <div class="location_details_hidden">
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= form.label :route %><br>
              <%= form.text_field :route, class: 'form-control' , value:"not-available", 'data-target'=> "maps.route",
                :readonly => true %>
          </div>
      
          <div class="form-group col-md-6">
            <%= form.label :street_number %><br>
              <%= form.text_field :street_number, class: 'form-control' , value:"not-available", 'data-target'=>
                "maps.street_number", :readonly => true %>
          </div>
        </div>
      
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= form.label :neighborhood %><br>
              <%= form.text_field :neighborhood, class: 'form-control' , value:"not-available", 'data-target'=>
                "maps.neighborhood", :readonly => true %>
          </div>
      
          <div class="form-group col-md-6">
            <%= form.label :postal_code %><br>
              <%= form.text_field :postal_code, class: 'form-control' , value:"not-available", 'data-target'=>
                "maps.postal_code", :readonly => true %>
          </div>
        </div>
      
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= form.label :locality %><br>
              <%= form.text_field :locality, class: 'form-control' , value:"not-available", 'data-target'=> "maps.locality",
                :readonly => true %>
          </div>
      
          <div class="form-group col-md-6">
            <%= form.label :country %><br>
              <%= form.text_field :country, class: 'form-control' , value:"not-available", 'data-target'=> "maps.country",
                :readonly => true %>
          </div>
        </div>
      </div>

      <%= render "jquery_toggles/location_details_toggle" %>
      
      <br />
      <br />
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.label :description, "Description" %>
          <%= form.text_area :description, placeholder: "max 100 character" , class:"form-control", maxlength: 100, rows: "3", :required => 'required' %>
        </div>
        <div class="form-group col-md-6">
          <%= form.label :other_info, "Other Info" %>
          <%= form.text_area :other_info, placeholder: "max 30 character" , class:"form-control", maxlength: 30, rows: "3" %>
        </div>
      </div>

      <br />

      <div class="form-row text-left">
        <div class="form-group col-md-12">
          <%= form.submit "Save", name: "form_on_submit", class: "btn btn-default btn-success" ,
            style: 'color:black; font-weight: bold; width: 15rem' %>
        </div>
      </div>

    </form>
  </div>


  <div class="column column_2">
    <form >
      <div class="form-group">
        <div data-maps-target="map" , class='map'></div>
      </div>
    </form>
  </div>
<hr />


<% end %>

app/views/pets/show.html.erb
<div class="container-fluid">

  <div class="row">
    
    <div class="col-6 mt-3">
      <div class="row">
        <div class="col-sm-12">
          <% if !@pet.image.blank? %>
            <%= image_tag(@pet.image, style: 'height:auto;width:100%;' ) %>
          <% else %>
            <p>No image available!</p>
          <% end %>
        </div>
      </div>


      <div class="row">
        <div class="col-sm-12">
          <%= render "comments/comment_handle" %>
        </div>
      </div>

    </div>
    

    <div class="col-6 mt-3">
        <div class="card border-0">
          <div class="card-body">
            <h4 class="card-title"> <strong><%= @pet.name.upcase %></strong></h4>
            
            <div class="row">
              <div class="col-sm-6">
                <p class="card-text"><strong>Lost on: </strong>
                <%= @pet.lost_on_format %> </p>
              </div>
              
              <div class="col-sm-6">
                <% if @pet.injured %>
                  <p class="card-text"><strong>Injured: </strong> Yes</p>
                <% else %>
                  <p class="card-text"><strong>Injured: </strong> No</p>
                <% end %>
              </div>
            </div>

            <hr />

            <div class="row">
              <div class="col-sm-6">
                <p class="card-text"><strong>Species: </strong>
                  <%= @pet.species %>
                </p>
              </div>
              <div class="col-sm-6">
                <p class="card-text"><strong>Breed: </strong>
                  <%= @pet.breed %>
                </p>
              </div>
            </div>

            <hr />
            
            <div class="row">
              <div class="col-sm-6">
                <p class="card-text"><strong>Location: </strong>
                  <%= @pet.find_record_details.locality %>
                </p>
              </div>
              <div class="col-sm-6">
                <p class="card-text"><strong>Country: </strong>
                  <%= @pet.find_record_details.country %>
                </p>
              </div>
            </div>

            <hr />
            
            <div class="row">
              <div class="col-sm-6">
                <p class="card-text"><strong>Route: </strong>
                  <%= @pet.find_record_details.route %>
                </p>
              </div>
              <div class="col-sm-6">
                <p class="card-text"><strong>Street Number: </strong>
                  <%= @pet.find_record_details.street_number %>
                </p>
              </div>
            </div>

            <hr />
            
            <div class="row">
              <div class="col-sm-6">
                <p class="card-text"><strong>Neighborhood </strong>
                  <%= @pet.find_record_details.neighborhood %>
                </p>
              </div>
              <div class="col-sm-6">
                <p class="card-text"><strong>Postal Code: </strong>
                  <%= @pet.find_record_details.postal_code %>
                </p>
              </div>
            </div>
            
            <hr />
            
            <div class="row">
              <div class="col-sm-12">
                <p class="card-text"><strong>Description: </strong>
                  <%= @pet.description %>
                </p>
              </div>
            </div>
            
            <hr />

            <div class="row">
              <div class="col-sm-12">
                <p class="card-text"><strong>Other Info: </strong>
                  <%= @pet.other_info %>
                </p>
              </div>
            </div>

        <br>

        <div class="card-footer text-muted text-center">
          last update <%= @pet.updated_at.strftime('%a, %d %b %Y %H:%M') %>
        </div>

        <% if user_signed_in? && @pet.user_id==current_user.id %>
          <div class="card-footer text-center">
              <%= link_to 'Edit' , edit_pet_path(@pet), class: "btn btn-primary btn-sm", style:"color: white; font-weight: bold" %> |
              <%= link_to 'Delete' , pets_delete_path(@pet), class: "btn btn-danger btn-sm", style:"color: black; font-weight: bold", method: :delete, onclick: "return confirm('Are you sure?')" %> 
            </div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>