config/routes.rb
Rails.application.routes.draw do
  get 'pets_toggle/index'
  devise_for :users, controllers: {registrations: "registrations"}
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :pets do
    delete 'pets/:id/image_remove', to: 'pets#remove_image', as: 'pet_image_remove'
    get '/pets/:id/image_remove' => 'pets#remove_image'
  end
  delete 'pets/:id/delete' => 'pets#destroy', as: 'pets_delete'
  get '/pets/:id/delete' => 'pets#destroy'

  resources :found_pets do
    delete 'found_pets/:id/image_remove', to: 'found_pets#remove_image', as: 'pet_image_remove'
    get '/found_pets/:id/image_remove' => 'found_pets#remove_image'
  end
  delete 'found_pets/:id/delete' => 'found_pets#destroy', as: 'found_pets_delete'
  get '/found_pets/:id/delete' => 'found_pets#destroy'

  root "home#index"
  get  'about/index', to:'about#index'
  get  'contact/index', to:'contact#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/home/index.html.erb
<div style="margin-top: 50px;">

<h2 class="text-center" style="font-family: Verdana, Geneva, Tahoma, sans-serif; color:rgb(33, 136, 56)"> Welcome to Paw Searchers</h2>

<hr />

<br />
<br />
<header>
  <div class="card-group">
  <div class="col-sm-4">
      <div class="card text-white bg-primary mb-3">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">Report <i>(create)</i> </h5>
          <p class="card-text">To report lost and found pets or abused strays, just click on the box below.</p>
          
          <div class="container">
            <%= link_to 'Lost Pets' , new_pet_path, style: 'color:#000000; font-weight:bold;', :class => "btn btn-danger" %>
            <%= link_to 'Found Pets' , new_found_pet_path, style:'color:#000000; float:right; font-weight:bold', :class => "btn btn-success" %>
          </div>
        </div>
      </div>
    </div>


    <div class="col-sm-4">
      <div class="card text-white bg-primary mb-3">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">Listings</h5>
          <p class="card-text">To browse lost and found pets or abused strays, just click on the box below.</p>

          <div class="container text-center">
            <%= link_to 'All Pets' , pets_toggle_index_path, style: 'color:#000000; font-weight:bold;', :class => "btn btn-warning" %>
      
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card text-white bg-primary mb-3">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">Google Map</h5>
          <p class="card-text">View the location of lost and found pets or abused strays, just click on the box below.</p>
          
          <div class="container">
            <a href="https://www.google.com/maps" target="_blank" class="btn btn-light" style="color: rgb(0, 0, 0);position:relative; left:60px; top:2px; font-weight: bold">Show On Map</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>