config/routes.rb
Rails.application.routes.draw do
  get 'pets_toggle/index'
  devise_for :users, controllers: {registrations: "registrations"}
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :pets do
    delete 'pets/:id/image_remove', to: 'pets#remove_image', as: 'pet_image_remove'
    get '/pets/:id/image_remove' => 'pets#remove_image'
  end
  delete 'pets/:id/delete' => 'pets#destroy', as: 'pets_delete'
  get '/pets/:id/delete' => 'pets#destroy'

  resources :found_pets do
    delete 'found_pets/:id/image_remove', to: 'found_pets#remove_image', as: 'pet_image_remove'
    get '/found_pets/:id/image_remove' => 'found_pets#remove_image'
  end
  delete 'found_pets/:id/delete' => 'found_pets#destroy', as: 'found_pets_delete'
  get '/found_pets/:id/delete' => 'found_pets#destroy'

  root "home#index"
  get  'about/index', to:'about#index'
  get  'contact/index', to:'contact#index'

end

app/views/nav/_navbar.html.erb
<nav class="navbar navbar-expand-lg">

  <a class="navbar-brand" 
     href="/"> 
     <%= image_tag '' %>
  </a>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Home' , root_path, class: 'nav-link' %>
      </li>
 
      <li class="nav-item">
        <%= link_to 'About' , about_index_path, class: 'nav-link' %>
      </li>
 
      <li class="nav-item">
        <%= link_to 'Contact' , contact_index_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Logout' , destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' },
            class: 'nav-link' %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to 'Login' , user_session_path, class: 'nav-link' %>
        </li>
        
        <li class="nav-item">
          <%= link_to 'SignUp' , new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>